# Generated by Django 3.1.8 on 2021-06-03 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('flashcard', '0002_auto_20210603_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.collection'),
        ),
    ]
