# Generated by Django 3.1.8 on 2021-06-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20210603_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.CharField(default='test', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='numberOfCards',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
